'use client';

import { useState } from 'react';
import { Check, X, RotateCcw } from 'lucide-react';

/* ---------------- Types ---------------- */

interface Question {
  question: string;
  options: string[];
  answer: number;
}

interface NoteSection {
  heading: string;
  items: string[];
}

type ViewType = 'notes' | 'practice' | 'quiz';

/* ---------------- Data ---------------- */

const notes: NoteSection[] = [
  {
    heading: '1. Cloud Computing Recap — "Anything"-as-a-Service',
    items: [
      'Cloud computing offers Software as a Service (SaaS), Platform as a Service (PaaS), and Infrastructure as a Service (IaaS), delivered on top of five core capabilities: on-demand self-service, resource pooling, broad network access, rapid elasticity, and measured services.',
      'This recap sets up the motivation for Fog computing: cloud-only architectures centralize everything in remote data centers, which creates problems for latency-sensitive and bandwidth-heavy IoT workloads.',
    ],
  },
  {
    heading: '2. Fog Computing — Motivation & Definition',
    items: [
      'Fog computing is a model in which data, processing, and applications are concentrated in devices at the network edge rather than existing almost entirely in the cloud.',
      'The term "Fog Computing" was introduced by Cisco Systems as a new model to ease wireless data transfer to distributed devices in the Internet of Things (IoT) network paradigm.',
      'The vision of fog computing is to enable applications on billions of connected devices to run directly at the network edge.',
    ],
  },
  {
    heading: '3. Cloud vs Fog Computing — Comparison',
    items: [
      'Latency and delay jitter: high in cloud computing vs low/very low in fog computing.',
      'Location of server nodes: within the internet for cloud vs at the edge of the local network for fog; distance between client and server is multiple hops for cloud vs one hop for fog.',
      'Security: undefined in cloud vs can be defined in fog; attack probability on the data enrouter is high for cloud vs very low for fog; location awareness is absent in cloud but present in fog.',
      'Geographical distribution: centralized for cloud vs distributed for fog; number of server nodes is few for cloud vs very large for fog.',
      'Support for mobility is limited in cloud vs supported in fog; real-time interactions are supported by both; last-mile connectivity is via leased line for cloud vs wireless for fog.',
    ],
  },
  {
    heading: '4. Cloud-Fog-Edge Computing',
    items: [
      'The vision is to bring intelligence down from the cloud close to the ground/end-user rather than keeping it centralized.',
      'Cellular base stations, network routers, and WiFi gateways become capable of running applications; end devices like sensors can perform basic data processing themselves.',
      'Processing close to devices lowers response time, enabling real-time applications; the hierarchy runs from Core (Cloud) through Fog to Edge (Locations).',
    ],
  },
  {
    heading: '5. Cloud–Fog–Edge: Issues and How Fog Helps',
    items: [
      'Cloud issues/limitations: latency, large volume of generated data, bandwidth requirement, and cloud architectures not being designed for the volume, variety, and velocity of data generated by IoT devices.',
      'IoT Device (Edge) issues: limited processing, storage, and power requirements on the devices themselves.',
      'Fog layer benefits: much lesser latency permitting real-time applications, less network congestion, reduced cost of execution at the cloud, more data location awareness, and better handling of the colossal data generated by sensors.',
    ],
  },
  {
    heading: '6. Case Study: Health Cloud-Fog-Edge — Architecture',
    items: [
      'A 5-level hierarchy carries information up and down: Level0 = Cloud, Level1 = ISP, Level2 = Area Gateway (AreaGW), Level3 = Mobile, Level4 = IoT devices.',
      'IoT devices in the case study include display units (disp) and fitness trackers (fitbit) that connect to mobile devices, which connect to an Area Gateway, which connects via an ISP up to the Cloud.',
    ],
  },
  {
    heading: '7. Case Study: Health Cloud-Fog-Edge — Device Configuration & Latency',
    items: [
      'Device configuration table specifies MIPS, RAM, uplink/downlink bandwidth, hierarchy level, cost per MIPS, busy power, and idle power for Cloud, ISP, AreaGW, and Mobile devices; only the Cloud has a non-zero cost per MIPS (0.01), while ISP, AreaGW, and Mobile have zero cost since they are owned by the organization.',
      'Latency values between components: Fitbit→Mobile = 1ms, Mobile→AreaGW = 2ms, AreaGW→ISP GW = 2ms, ISP GW→Cloud = 100ms, Mobile→Display = 1ms — showing that reaching the cloud incurs by far the largest latency.',
    ],
  },
  {
    heading: '8. Case Study: Typical Application Components and Flow',
    items: [
      'The health application is composed of modules: Client Module (interfaces with EEG sensor input and Display output), Data Filtering Module, Data Processing Module, Event Handler Module, and Confirmatory Module.',
      'Data flows from the Client Module to the Data Filtering Module, then to the Data Processing Module and Event Handler Module, with the Event Handler Module triggering the Confirmatory Module when needed.',
    ],
  },
  {
    heading: '9. Case Study: Simulation of Health Cloud-Fog Model',
    items: [
      'Placement of application modules differs between Fog-based and Cloud-based models: in the Fog-based model, the Client Module runs on Mobile, while Data Filtering, Data Processing, and Event Handler Modules run on the Area Gateway, and only the Confirmatory Module runs on the Cloud.',
      'In the Cloud-based model, only the Client Module stays on Mobile; all other modules (Data Filtering, Data Processing, Event Handler, and Confirmatory) run on the Cloud.',
      'iFogSim was used to simulate different physical topology configurations, scaling from Configuration 1 (1 AreaGW, 4 total users) up to Configuration 5 (16 AreaGWs, 64 total users).',
    ],
  },
  {
    heading: '10. Case Study: Performance Analysis — Network Usage',
    items: [
      'Network usage is very low for the Fog architecture because only for a few positive cases is the Confirmatory Module (residing on the Cloud) actually accessed.',
      'For the Cloud-based architecture, network usage is high because all modules now reside on the Cloud, so every request must traverse the network to reach them.',
      'This gap widens as configurations scale up (Config 1 to Config 5), with Cloud-based network usage growing much faster than Fog-based usage.',
    ],
  },
  {
    heading: '11. Case Study: Performance Analysis — Execution Cost',
    items: [
      'Only the resources on the Cloud incur a monetary cost; other resources (ISP, AreaGW, Mobile) are owned by the organization and are cost-free in this model.',
      'More processing at the Cloud leads to higher costs under the Cloud-based architecture; the Fog-based architecture keeps execution cost far lower across all configurations since most processing stays off the Cloud.',
    ],
  },
  {
    heading: '12. Case Study: Performance Evaluation — Latency',
    items: [
      'Latency of the control loop is fixed and low in the Fog architecture because the application modules that form part of the control loop are located at the Area Gateway itself.',
      'In the Cloud-based architecture, those modules are located at the datacenter, so latency rises sharply as the configuration scales (visible especially from Config 3 onward).',
    ],
  },
  {
    heading: '13. Case Study: Energy Consumption',
    items: [
      'Energy consumption is broken down into DC (data center) Energy, Mobile Energy, and Edge Energy across different configurations and architectures (Fog vs Cloud).',
      'Mobile Energy consumption is markedly higher under the Cloud-based architecture at larger configurations (e.g., Config 4) compared to the Fog-based architecture, since mobile devices must communicate further to reach the cloud.',
    ],
  },
  {
    heading: '14. Case Study: Prototype Implementation',
    items: [
      'A lab-based setup used Raspberry Pi devices as Fog devices and AWS as the Cloud.',
      'The prototype allowed using different datasets and customizing formulae for analysis, and permitted changes in Resource Allocation Policy in terms of customized physical devices, customized requirements of application modules, and the module placement policy.',
    ],
  },
  {
    heading: '15. Resource Management — Challenges in "Cloud-only" Scenario',
    items: [
      'Processing IoT applications directly in the cloud may not be the most efficient solution for each IoT scenario, especially for time-sensitive applications.',
      'A promising alternative is to use fog and edge computing, which address the issue of managing the large data bandwidth needed by end devices by processing large amounts of generated data close to the data sources rather than in the cloud.',
      'A key consideration in cloud-based IoT environments is resource management, which typically revolves around resource allocation, workload balance, resource provisioning, task scheduling, and QoS to achieve performance improvements.',
    ],
  },
  {
    heading: '16. Fog-Edge to Support Cloud Computing',
    items: [
      'A pure cloud-only approach may involve transporting data from each single sensor to a data center over a network, processing it there, and then sending instructions back to actuators — introducing a latency issue.',
      'Fog and edge computing are not substitutes for cloud computing; they do not completely replace it. Instead, the three technologies work together to grant improved latency, reliability, and faster response times.',
      'A typical cloud–fog environment model is composed of three layers: a client layer (edge), a fog layer, and a cloud layer; the fog layer aims to satisfy resource requirements for clients, and if fog-layer resources are insufficient, the request is passed up to the cloud layer.',
      'Main functional components: the Fog Server Manager employs all available processors for the client; Virtual Machines (VMs) operate on the fog data server, process requests, and deliver results back to the Fog Server Manager; fog servers use a "server virtualization technique" to manage requests.',
      'The general trend is to decentralize computing resources from large cloud data centers toward the network edge, either via dedicated "micro" data centers or via internet nodes (routers, gateways, switches) augmented with computing capability — a model using only edge resources is "edge computing," while one using both edge resources and the cloud together is "fog computing."',
    ],
  },
  {
    heading: '17. Resource Management in Cloud-Fog-Edge — Overview',
    items: [
      'Resource management in fog/edge computing can be organized around three pillars: Architectures, Infrastructure, and Algorithms.',
      'Architectures are classified by Data Flow, Control, and Tenancy.',
      'Infrastructure is composed of Hardware, System Software, and Middleware.',
      'Algorithms cover Discovery, Benchmarking, Load-balancing, and Placement.',
    ],
  },
  {
    heading: '18. Resource Management Approaches — Architectures',
    items: [
      'Data Flow: based on the direction of movement of workloads and data in the computing ecosystem — for example, workloads transferred from user devices to edge nodes, or from cloud servers to edge nodes (sub-categories: aggregation, sharing, offloading).',
      'Control: based on how resources are controlled — a single controller/central algorithm may manage a number of edge nodes (centralized), or a distributed approach may be employed; a hierarchical approach is also possible.',
      'Tenancy: based on the support provided for hosting multiple entities — either a single application (single-tenant) or multiple applications (multi-tenant) could be hosted on an edge node.',
    ],
  },
  {
    heading: '19. Resource Management Approaches — Infrastructure',
    items: [
      'Hardware: fog/edge computing exploits small-form-factor devices such as network gateways, WiFi Access Points, set-top boxes, small home servers, edge ISP servers, cars, and even drones as compute servers for resource efficiency, as well as commodity products such as desktops, laptops, and smartphones.',
      'System Software: runs directly on fog/edge hardware resources (CPU, memory, network devices); it manages resources and distributes them to fog/edge applications — examples include operating systems and virtualization software.',
      'Middleware: runs on top of an operating system and provides complementary services not supported by the system software, coordinating distributed compute nodes and performing deployment of VMs or containers to each fog/edge node.',
    ],
  },
  {
    heading: '20. Resource Management Approaches — Algorithms',
    items: [
      'Discovery: identifying edge resources so that workloads from the cloud or from user devices/sensors can be deployed on them (sub-areas: programming infrastructure, handshaking protocol, message passing).',
      'Benchmarking: capturing the performance of entities like CPU, storage, and network of a computing system (sub-areas: evaluating functional properties, application benchmarking, integrated benchmarking).',
      'Load-balancing: as edge data centers are deployed across the network edge, distributing tasks efficiently has gained significant attention; typical techniques include optimization techniques, cooperative load balancing, graph-based balancing, and breadth-first search.',
      'Placement: addresses the issue of placing incoming computation tasks on suitable fog/edge resources, considering resource availability in the fog/edge layer and environmental changes; approaches include dynamic condition-aware techniques and iterative techniques.',
    ],
  },
  {
    heading: '21. Service Placement Problem in Fog and Edge Computing',
    items: [
      'Fog Computing is a highly virtualized platform that offers computational resources, storage, and control between end-users and Cloud servers.',
      'It is a new paradigm in which a centralized Cloud coexists with distributed edge nodes, where local and global analyses are performed at edge devices or forwarded to the Cloud.',
      'Fog infrastructure consists of IoT devices (End layer), Fog Nodes, and at least one Cloud Data Center (Cloud layer), with characteristics including location awareness and low latency, better bandwidth utilization, scalability, and support for mobility.',
      'A Fog orchestrator (with a Resource Manager, Planner, and Status Monitor) coordinates fog nodes (local compute, data cache, storage, agent) and interacts with the Cloud data center; the Fog layer handles real-time data collection, processing, caching, and load-balancing, while the Cloud layer handles massive data processing and massive machine learning.',
    ],
  },
  {
    heading: '22. Service Placement Problem — Taxonomy',
    items: [
      'Problem statement is broken into: Infrastructure model, Application model, and Deployment pattern.',
      'Service placement taxonomy covers: Control plane design, Placement characteristic, System dynamicity, and Mobility support.',
      'Optimization Strategies cover: Optimization objective and metrics, Problem formulation, and Resolution strategies.',
      'Evaluation environments include: Analytical tools, Simulators, and Experimental testbeds.',
    ],
  },
  {
    heading: '23. Deployment (Application Placement) on Cloud-Fog-Edge Framework',
    items: [
      'An example application (an augmented-reality pipeline) has stages: vision capture, coarse feature extraction, face recognition, object recognition, optical character recognition (OCR), learning-based activity inference, rendering, and effect display.',
      'These stages can be mapped onto physical devices such as Google Glass, a local laptop, a smart WiFi gateway, a LAN router, a cloudlet, a WAN gateway, and a backend cloud — illustrating how application components get distributed across the cloud-fog-edge hierarchy.',
    ],
  },
  {
    heading: '24. Application Placement on Cloud-Fog-Edge Framework',
    items: [
      'The application placement problem defines a mapping pattern by which application components and links are mapped onto an infrastructure graph (i.e., computing devices and physical edges).',
      'Application placement involves finding available resources in the network (nodes and links) that satisfy application requirements, satisfy constraints, and optimize the objective — e.g., respecting service requirements, not exceeding resource capacities, satisfying locality constraints, and minimizing energy consumed.',
      'Service providers must account for these constraints to (i) limit the search space and (ii) provide an optimum or near-optimum placement.',
    ],
  },
  {
    heading: '25. Application Placement — Constraints',
    items: [
      'Resource constraints: an infrastructure node is limited by finite capabilities in terms of CPU, RAM, storage, bandwidth, etc., which must be considered while placing application/service components.',
      'Network constraints: constraints such as latency and bandwidth must be considered when deploying applications.',
      'Application constraints: locality requirement restricts certain services\u2019 executions to specific locations; delay sensitivity means some applications specify a deadline for a processing operation or for deploying the whole application in the network.',
    ],
  },
  {
    heading: '26. Service Placement — Optimization Strategies',
    items: [
      'Optimizing the service placement problem in a Cloud-Fog infrastructure can have several different objectives, with different formulations and diverse algorithm proposals.',
      'Common optimization objectives and metrics include: latency, resource utilization, cost, and energy consumption.',
    ],
  },
  {
    heading: '27. Offloading — Application and Data',
    items: [
      'Offloading is a technique in which a server, an application, and the associated data are moved onto the edge of the network.',
      'It augments (i) the computing requirements of individual or a collection of user devices, and (ii) brings services in the cloud that process requests from devices closer to the source.',
      'Offloading from User Device to Edge: augments computing in user devices by making use of edge nodes (usually a single hop away), via (i) Application partitioning and (ii) Caching mechanisms.',
      'Offloading from the Cloud to the Edge: a workload is moved from the cloud to the edge, via (i) Server offloading and (ii) Caching mechanisms.',
    ],
  },
  {
    heading: '28. Offloading Techniques — Details',
    items: [
      'From Device to Edge — Application Partitioning approaches: Brute Force, Greedy Heuristic, Simulated Annealing, Fuzzy Logic; partitioning models: Graph-based, Component-based, Neural Network-based.',
      'From Device to Edge — Caching Mechanisms: Chunking and Aggregation, Reverse Auction Game-based approaches.',
      'From Cloud to Edge — Server Offloading covers Replication (Database Cloning, Application Specific Data Replication) and Partitioning (parameters: Latency-aware, Functionality-aware, Geography-aware; approach: Manual).',
      'From Cloud to Edge — Caching Mechanisms: Content Popularity-based and Multi-layer caching.',
    ],
  },
  {
    heading: '29. Control Architectures',
    items: [
      'Control architectures for service placement fall into two broad categories: Centralized and Distributed.',
      'Centralized approaches include Solver-based and Graph Matching-based methods.',
      'Distributed approaches include Blockchain-based, Game Theoretic Approach-based, and Genetic Algorithm-based methods.',
    ],
  },
  {
    heading: '30. Hardware for Fog/Edge Computing',
    items: [
      'Fog/edge computing forms a computing environment that uses low-power devices — namely mobile devices, routers, gateways, and home systems.',
      'The combination of these small-form-factor devices, connected over the network, enables a cloud-like computing environment that can be leveraged by a rich set of applications processing Internet of Things (IoT) and cyber-physical systems (CPS) data.',
      'Hardware is further divided into Computation Devices (Single-board Computers, Commodity Products) and Network Devices (Gateways and Routers, WiFi APs, Edge Racks).',
    ],
  },
  {
    heading: '31. System Software for Fog/Edge Computing',
    items: [
      'System software for the fog/edge is a platform designed to operate directly on fog/edge devices, managing the computation, network, and storage resources of those devices.',
      'System software needs to support multi-tenancy and isolation, because fog/edge computing accommodates several applications from different tenants.',
      'Two categories: System Virtualization (Virtual Machines, Containers, VM/Container Migration) and Network Virtualization (Software-Defined Networking (SDN) & Network Function Virtualization (NFV), Overlay Network).',
    ],
  },
  {
    heading: '32. Middleware for Fog/Edge Computing',
    items: [
      'Middleware provides complementary services to system software, including performance monitoring, coordination and orchestration, and communication facilities/protocols.',
      'Middleware categories include: Volunteer Edge Computing, Hierarchical Fog/Edge Computing, Mobile Fog/Edge Computing, and Cloud Orchestration Management.',
    ],
  },
  {
    heading: '33. Algorithms for Fog/Edge Computing — Detail',
    items: [
      'Discovery: identifying edge resources within the network that can be used for distributed computation (programming infrastructure, handshaking protocol, message passing).',
      'Benchmarking: capturing the performance of resources for decision-making to maximize deployment performance (evaluating functional properties, application benchmarking, integrated benchmarking).',
      'Load-balancing: distributing workloads across resources based on different criteria such as priorities and fairness (optimization, cooperative load-balancing, graph-based, breadth-first search).',
      'Placement: identifying resources appropriate for deploying a workload (dynamic condition-aware; iterative techniques — iterative over resources or iterative over the problem space).',
    ],
  },
  {
    heading: '34. Cloud Federation — Definition',
    items: [
      'A federated cloud (also called cloud federation) is the deployment and management of multiple external and internal cloud computing services to match business needs.',
      'A federation is the union of several smaller parts that perform a common action.',
      'Cloud federation represents collaboration between Cloud Service Providers (CSPs) to achieve: capacity utilization, inter-operability, a catalog of services, and insight about providers and SLAs.',
    ],
  },
  {
    heading: '35. Cloud Federation — Motivation',
    items: [
      'Different CSPs join together to form a federation.',
      'Benefits include: maximizing resource utilization, minimizing power consumption, load balancing, achieving global utility, and expanding a CSP\u2019s global footprint.',
    ],
  },
  {
    heading: '36. Cloud Federation — Characteristics',
    items: [
      'Federation aims to overcome current limitations of cloud computing such as service interruptions, lack of interoperability, and degradation of services; cloud federation is an example of a broader category of proposed inter-cloud organizations.',
      'It is an inter-cloud organization with voluntary characteristics, ideally with maximum geographical separation, a well-defined marketing system, and a regulated federal agreement.',
      'It is an environment where multiple service providers come together and share their resources.',
    ],
  },
  {
    heading: '37. Federation Architecture — Coupling Levels',
    items: [
      'Cloud federation is associated with several portability and interoperability issues. Typical federation architectures are: cloud bursting, brokering, aggregation, and multitier.',
      'These architectures can be classified according to the level of coupling or interoperation among the cloud instances involved, ranging from loosely coupled (little or no interoperability) to tightly coupled (full interoperability among cloud instances).',
    ],
  },
  {
    heading: '38. Loosely Coupled Federation',
    items: [
      'Involves limited interoperation between CSPs/cloud instances — for example, a private cloud complementing its infrastructure with resources from an external commercial cloud.',
      'A CSP has little or no control over remote resources (e.g., decisions about VM placement are not allowed), monitoring information is limited (e.g., only CPU, memory, or disk consumption of each VM is reported), and there is no support for advanced features such as cross-site networks or VM migration.',
    ],
  },
  {
    heading: '39. Partially Coupled Federation',
    items: [
      'Different CSPs (partner clouds) establish a contract or framework agreement stating the terms and conditions under which one partner cloud can use resources from another.',
      'This contract can enable a certain level of control over remote resources (e.g., allowing affinity rules to force remote VMs onto the same physical cluster), may agree to interchange more detailed monitoring information (e.g., host location, energy consumption), and may enable some advanced networking features (e.g., virtual networks across site boundaries).',
    ],
  },
  {
    heading: '40. Tightly Coupled Federation',
    items: [
      'In this case, the clouds are normally governed by the same cloud administration.',
      'A cloud instance can have advanced control over remote resources — e.g., allowing decisions about the exact placement of a remote VM — and can access all monitoring information available about remote resources.',
      'May allow other advanced features, including creation of cross-site networks, cross-site migration of VMs, implementation of high-availability techniques among remote cloud instances, and creation of virtual storage systems across site boundaries.',
    ],
  },
  {
    heading: '41. Cloud Federation Architectures — Hybrid/Bursting',
    items: [
      'Cloud bursting (hybrid) architecture combines existing on-premise infrastructure (usually a private cloud) with remote resources from one or more public clouds to provide extra capacity to satisfy peak demand periods.',
      'Since the local cloud OS has no advanced control over virtual resources deployed in external clouds beyond the basic operations the providers allow, this architecture is loosely coupled.',
      'Most existing open cloud managers support the hybrid cloud architecture.',
    ],
  },
  {
    heading: '42. Cloud Federation Architectures — Broker',
    items: [
      'A broker serves various users and has access to several public cloud infrastructures; a simple broker should be able to deploy virtual resources in the cloud selected by the user. Brokering is the most common federation scenario.',
      'An advanced broker offering service management capabilities could make scheduling decisions based on optimization criteria such as cost, performance, or energy consumption, to automatically deploy a user\u2019s virtual service in the most suitable cloud, potentially distributing service components across multiple clouds.',
      'This architecture is also loosely coupled, since public clouds typically do not allow advanced control over the deployed virtual resources.',
    ],
  },
  {
    heading: '43. Cloud Federation Architectures — Aggregated',
    items: [
      'Involves two or more partner clouds that interoperate to aggregate their resources and provide users with a larger virtual infrastructure.',
      'This architecture is usually partially coupled, since partners could be provided with some kind of advanced control over remote resources, depending on the terms and conditions of contracts with other partners.',
      'Partner clouds usually have a higher coupling level when they belong to the same corporation than when they are owned by different companies that agree to cooperate and aggregate resources.',
    ],
  },
  {
    heading: '44. Cloud Federation Architectures — Multitier',
    items: [
      'Involves two or more cloud sites, each running its own cloud OS and usually belonging to the same corporation, managed by a third cloud OS instance following a hierarchical arrangement.',
      'This root/top cloud OS instance has full control over resources in different cloud sites — a tightly coupled scenario — and exposes the resources available in different cloud sites as if they were located in a single cloud.',
      'This architecture is beneficial for corporations with geographically distributed cloud infrastructures because it provides uniform access, and may be useful for implementing advanced management features such as high availability, load balancing, and fault tolerance.',
    ],
  },
];

const questions: Question[] = [
  { question: 'Fog computing is a model in which data, processing, and applications are concentrated:', options: ['Entirely in the cloud', 'In devices at the network edge rather than almost entirely in the cloud', 'Only on mainframes', 'Only in the client\u2019s browser'], answer: 1 },
  { question: 'Which company introduced the term "Fog Computing"?', options: ['Cisco Systems', 'Google', 'Amazon', 'IBM'], answer: 0 },
  { question: 'The vision of fog computing is to enable applications on billions of connected devices to run:', options: ['Only in the cloud', 'Directly at the network edge', 'Only on mainframes', 'Only via satellite'], answer: 1 },
  { question: 'Compared to cloud computing, latency in fog computing is:', options: ['Higher', 'Low', 'Unmeasurable', 'Irrelevant'], answer: 1 },
  { question: 'In the Cloud vs Fog comparison, the location of server nodes in fog computing is:', options: ['Within the internet', 'At the edge of the local network', 'Only in outer space', 'Undefined'], answer: 1 },
  { question: 'In fog computing, the distance between the client and server is typically:', options: ['Multiple hops', 'One hop', 'Infinite hops', 'Not applicable'], answer: 1 },
  { question: 'Regarding security, fog computing compared to cloud computing:', options: ['Has undefined security', 'Can have security that is defined, with less attack probability on data enrouter', 'Has no security at all', 'Is always less secure'], answer: 1 },
  { question: 'Geographical distribution of server nodes in fog computing is typically:', options: ['Centralized', 'Distributed', 'Nonexistent', 'Single-node only'], answer: 1 },
  { question: 'Support for mobility in fog computing compared to cloud computing is:', options: ['Limited compared to cloud', 'Supported, versus limited support in cloud', 'Not applicable', 'Identical to cloud in every case'], answer: 1 },
  { question: 'The last-mile connectivity type typically used in fog computing is:', options: ['Leased line', 'Wireless', 'Fiber only', 'Satellite only'], answer: 1 },
  { question: 'In Cloud-Fog-Edge computing, intelligence is brought:', options: ['Down from the cloud close to the ground/end-user', 'Up from the edge into orbit', 'Nowhere new', 'Only into mainframes'], answer: 0 },
  { question: 'Which devices, according to the notes, are capable of running applications in a Cloud-Fog-Edge model?', options: ['Cellular base stations, network routers, WiFi gateways', 'Only desktop PCs', 'Only smart watches', 'Only tape drives'], answer: 0 },
  { question: 'Processing close to devices in Cloud-Fog-Edge computing:', options: ['Increases response time', 'Lowers response time, enabling real-time applications', 'Has no effect on response time', 'Only works for batch jobs'], answer: 1 },
  { question: 'Which of the following is listed as a "Cloud Issues Limitation" motivating fog computing?', options: ['Latency and bandwidth requirement', 'Excess battery life on IoT devices', 'Too few connected devices', 'Zero data being generated'], answer: 0 },
  { question: 'Which of the following is listed as an IoT Device (Edge) issue?', options: ['Processing, storage, and power requirement limitations', 'Unlimited processing power', 'Unlimited storage', 'No power constraints'], answer: 0 },
  { question: 'A benefit of the Fog layer mentioned in the notes is:', options: ['Much lesser latency permitting real-time applications', 'Higher network congestion', 'Increased cost of execution at cloud', 'Less location awareness'], answer: 0 },
  { question: 'In the Health Cloud-Fog-Edge case study, Level0 corresponds to:', options: ['Cloud', 'ISP', 'AreaGW', 'Mobile'], answer: 0 },
  { question: 'In the Health Cloud-Fog-Edge case study, Level4 corresponds to:', options: ['Cloud', 'ISP', 'Mobile', 'IoT devices'], answer: 3 },
  { question: 'In the case study device configuration table, which device has a non-zero cost per MIPS?', options: ['Cloud', 'ISP', 'AreaGW', 'Mobile'], answer: 0 },
  { question: 'In the case study latency table, which link has the highest latency?', options: ['Fitbit to Mobile', 'Mobile to Area GW', 'Area GW to ISP GW', 'ISP GW to Cloud'], answer: 3 },
  { question: 'In the typical application components and flow diagram, which module directly interfaces with the EEG sensor and Display?', options: ['Client Module', 'Data Filtering Module', 'Data Processing Module', 'Confirmatory Module'], answer: 0 },
  { question: 'In the Fog-based simulation model, where is the Client Module placed?', options: ['Cloud', 'Mobile', 'ISP', 'AreaGW'], answer: 1 },
  { question: 'In the Fog-based simulation model, where are the Data Filtering, Data Processing, and Event Handler Modules placed?', options: ['Mobile', 'Area Gateway', 'ISP', 'Confirmatory server'], answer: 1 },
  { question: 'In the Fog-based simulation model, where is the Confirmatory Module placed?', options: ['Mobile', 'Area Gateway', 'Cloud', 'ISP'], answer: 2 },
  { question: 'In the Cloud-based simulation model, which module remains on Mobile?', options: ['Only the Client Module', 'All modules', 'Only the Confirmatory Module', 'None'], answer: 0 },
  { question: 'Which toolkit was used to simulate different physical topology configurations in the case study?', options: ['iFogSim', 'MATLAB only', 'Excel Solver', 'CloudSim GUI'], answer: 0 },
  { question: 'According to the performance analysis, network usage in the Fog architecture is:', options: ['Very high', 'Very low, since the Confirmatory module on Cloud is rarely accessed', 'Identical to Cloud architecture', 'Undefined'], answer: 1 },
  { question: 'According to the performance analysis, network usage in the Cloud-based architecture is:', options: ['Very low', 'High, since all modules are now on Cloud', 'Zero', 'Only relevant for Config 1'], answer: 1 },
  { question: 'In the execution cost case study, which resources incur monetary cost?', options: ['Only resources on the Cloud', 'All resources equally', 'Only Mobile devices', 'Only the ISP'], answer: 0 },
  { question: 'More processing at the Cloud leads to:', options: ['Lower costs', 'Higher costs in the Cloud-based architecture', 'No change in cost', 'Free processing always'], answer: 1 },
  { question: 'In the latency performance evaluation, why is latency fixed and low in the Fog architecture?', options: ['Application modules forming the control loop are located at the Area Gateway itself', 'There is no network at all', 'The cloud is closer than the edge', 'Latency is randomly generated'], answer: 0 },
  { question: 'In the Cloud-based architecture for the health case study, control loop modules are located:', options: ['At the Area Gateway', 'At the Datacenter', 'On the Fitbit device', 'Nowhere'], answer: 1 },
  { question: 'In the energy consumption case study, which three categories of energy are compared?', options: ['DC Energy, Mobile Energy, Edge Energy', 'Solar Energy, Wind Energy, Battery Energy', 'CPU Energy, GPU Energy, RAM Energy', 'Kinetic, Potential, Thermal'], answer: 0 },
  { question: 'In the prototype implementation case study, what served as the Fog Devices?', options: ['Raspberry Pi', 'Mainframes', 'Smartphones only', 'Punch card machines'], answer: 0 },
  { question: 'In the prototype implementation case study, what served as the Cloud?', options: ['AWS', 'A local server closet', 'A single laptop', 'None, it was purely simulated'], answer: 0 },
  { question: 'Processing IoT applications directly in the cloud may not be efficient especially for:', options: ['Time-sensitive applications', 'Static archival data', 'Applications with no users', 'Applications that never run'], answer: 0 },
  { question: 'One of the considerations of cloud-based IoT environments, per the notes, is:', options: ['Resource management (allocation, workload balance, provisioning, scheduling, QoS)', 'Ignoring all workloads', 'Removing all scheduling', 'Disabling QoS entirely'], answer: 0 },
  { question: 'According to the notes, fog and edge computing relative to cloud computing are:', options: ['Complete substitutes that eliminate the cloud', 'Not substitutes; they work together with the cloud', 'Entirely unrelated to cloud computing', 'Only used for storage, never computation'], answer: 1 },
  { question: 'The cloud–fog environment model is typically composed of how many layers?', options: ['One layer', 'Two layers', 'Three layers: client (edge), fog, and cloud', 'Five layers'], answer: 2 },
  { question: 'If there is no/limited availability of resources in the fog layer, the request is:', options: ['Dropped permanently', 'Passed to the cloud layer', 'Sent back to the sensor unprocessed', 'Ignored'], answer: 1 },
  { question: 'The Fog Server Manager, per the notes, is responsible for:', options: ['Employing all available processors to the client', 'Only billing', 'Only marketing', 'Only physical security'], answer: 0 },
  { question: 'Virtual machines in the fog data server, per the notes, do what after processing?', options: ['Deliver results to the Fog Server Manager', 'Delete themselves', 'Send results directly to the ISP only', 'Nothing'], answer: 0 },
  { question: 'A computing model that uses only resources located at the edge of the network is called:', options: ['Edge computing', 'Fog computing', 'Grid computing', 'Quantum computing'], answer: 0 },
  { question: 'A model that uses both edge resources and the cloud together is referred to as:', options: ['Edge computing', 'Fog computing', 'Serverless computing', 'Mainframe computing'], answer: 1 },
  { question: 'Resource management approaches for fog/edge computing are organized around which three pillars?', options: ['Architectures, Infrastructure, Algorithms', 'Marketing, Sales, Support', 'Hardware only', 'Software only'], answer: 0 },
  { question: 'Resource management "Architectures" are classified on the basis of:', options: ['Data flow, control, and tenancy', 'Color scheme and font', 'Employee count', 'Marketing budget'], answer: 0 },
  { question: 'Resource management "Data Flow" is based on:', options: ['The direction of movement of workloads and data in the ecosystem', 'The number of employees', 'The color of the server rack', 'The price of electricity only'], answer: 0 },
  { question: 'Resource management "Control" is based on:', options: ['How resources are controlled (single controller vs distributed approach)', 'The physical color of routers', 'Employee scheduling', 'Marketing strategy'], answer: 0 },
  { question: 'Resource management "Tenancy" is based on:', options: ['Support for hosting multiple entities (single vs multiple applications)', 'The number of buildings owned', 'Only single-user access with no exceptions', 'Marketing tenancy agreements'], answer: 0 },
  { question: 'Which of the following is a hardware example used in fog/edge computing per the notes?', options: ['Network gateways, WiFi APs, set-top boxes, small home servers, drones', 'Only supercomputers', 'Only punch cards', 'Only mainframes from the 1970s'], answer: 0 },
  { question: 'System software for fog/edge computing runs directly on:', options: ['Fog/edge hardware resources like CPU, memory, network devices', 'Only in the browser', 'Only on paper', 'Nowhere; it is theoretical only'], answer: 0 },
  { question: 'System software needs to support multi-tenancy and isolation because:', options: ['Fog/edge computing accommodates several applications from different tenants', 'There is only ever one application running', 'Isolation is illegal', 'Multi-tenancy is banned in fog computing'], answer: 0 },
  { question: 'The two categories of system software mentioned are:', options: ['System Virtualization and Network Virtualization', 'Marketing Software and Sales Software', 'Only Word Processors', 'Only Spreadsheets'], answer: 0 },
  { question: 'Middleware in fog/edge computing provides:', options: ['Performance monitoring, coordination and orchestration, communication facilities', 'Only cosmetic UI themes', 'Only advertising', 'Nothing useful'], answer: 0 },
  { question: 'Which of the following is a middleware category mentioned in the notes?', options: ['Volunteer Edge Computing', 'Volunteer Marketing', 'Volunteer HR', 'Volunteer Finance'], answer: 0 },
  { question: 'The four major algorithms used to facilitate fog/edge computing are:', options: ['Discovery, Benchmarking, Load-balancing, Placement', 'Marketing, Sales, Support, Billing', 'Only Discovery', 'Only Placement'], answer: 0 },
  { question: '"Discovery" in fog/edge algorithms refers to:', options: ['Identifying edge resources within the network usable for distributed computation', 'Discovering new marketing leads', 'Finding new employees', 'Locating lost devices only'], answer: 0 },
  { question: '"Benchmarking" in fog/edge algorithms refers to:', options: ['Capturing the performance of resources for decision-making', 'Setting company benchmarks for sales', 'Measuring employee productivity', 'Grading students'], answer: 0 },
  { question: '"Load-balancing" in fog/edge algorithms refers to:', options: ['Distributing workloads across resources based on priorities, fairness, etc.', 'Balancing a company\u2019s financial books', 'Balancing employee schedules', 'Balancing marketing budgets'], answer: 0 },
  { question: '"Placement" in fog/edge algorithms refers to:', options: ['Identifying resources appropriate for deploying a workload', 'Placing advertisements', 'Placing furniture in an office', 'Placing orders for hardware'], answer: 0 },
  { question: 'Fog Computing is described in the Service Placement notes as:', options: ['A highly virtualized platform offering computational resources, storage, and control between end-users and Cloud servers', 'A physical-only, non-virtualized system', 'A replacement for all networking', 'A single monolithic server'], answer: 0 },
  { question: 'In the Service Placement Problem notes, Fog infrastructure consists of:', options: ['IoT devices (End layer), Fog Nodes, and at least one Cloud Data Center', 'Only IoT devices', 'Only Cloud Data Centers', 'Only Fog Nodes'], answer: 0 },
  { question: 'Which of the following is a characteristic of Fog Computing mentioned in the Service Placement notes?', options: ['Location awareness and low latency', 'High latency only', 'No support for mobility', 'No bandwidth utilization improvement'], answer: 0 },
  { question: 'The Fog orchestrator, per the notes, includes which components?', options: ['Resource manager, Planner, Status monitor', 'CPU, RAM, Disk only', 'Marketing, Sales, HR', 'None of these'], answer: 0 },
  { question: 'The Fog layer, per the Service Placement diagram, handles:', options: ['Real-time data collection, processing, caching, agenting, load-balancing', 'Only long-term archival storage', 'Only billing', 'Only marketing analytics'], answer: 0 },
  { question: 'The Cloud layer, per the Service Placement diagram, handles:', options: ['Massive data processing and massive machine learning', 'Only real-time sensor readings', 'Only local caching', 'Nothing; it is idle'], answer: 0 },
  { question: 'The Service Placement Problem taxonomy divides "Problem statement" into:', options: ['Infrastructure model, Application model, Deployment pattern', 'Marketing model, Sales model, HR model', 'Only Infrastructure model', 'Only Deployment pattern'], answer: 0 },
  { question: 'The Service Placement taxonomy\u2019s "Service placement taxonomy" branch includes:', options: ['Control plane design, Placement characteristic, System dynamicity, Mobility support', 'Only mobility support', 'Only control plane design', 'Marketing taxonomy'], answer: 0 },
  { question: 'The Service Placement taxonomy\u2019s "Optimization Strategies" branch includes:', options: ['Optimization objective and metrics, Problem formulation, Resolution strategies', 'Only problem formulation', 'Marketing strategies', 'HR strategies'], answer: 0 },
  { question: 'The Service Placement taxonomy\u2019s "Evaluation environments" branch includes:', options: ['Analytical tool, Simulator, Experimental testbeds', 'Only simulators', 'Only spreadsheets', 'Only marketing surveys'], answer: 0 },
  { question: 'In the Deployment (Application Placement) example, which device hosts the "Vision capture" and "Coarse feature extraction" stages?', options: ['Google Glass', 'Backend cloud', 'WAN gateway', 'Cloudlet'], answer: 0 },
  { question: 'In the Deployment example diagram, which component hosts the Cloudlet?', options: ['LAN router area, alongside the cloudlet node itself', 'Google Glass', 'The local laptop only', 'A smart WiFi gateway only'], answer: 0 },
  { question: 'The Application Placement problem defines:', options: ['A mapping pattern by which application components and links are mapped onto an infrastructure graph', 'A marketing campaign structure', 'An HR onboarding process', 'A billing invoice format'], answer: 0 },
  { question: 'Application placement involves finding resources that:', options: ['Satisfy application requirements and constraints while optimizing the objective', 'Are the cheapest regardless of requirements', 'Are randomly selected', 'Are always located in a single data center'], answer: 0 },
  { question: 'Service providers must account for placement constraints in order to:', options: ['Limit the search space and provide an optimum or near-optimum placement', 'Increase costs unnecessarily', 'Ignore locality requirements', 'Avoid using any algorithms'], answer: 0 },
  { question: 'Which of the following is a resource constraint in application placement?', options: ['Finite CPU, RAM, storage, and bandwidth capabilities of infrastructure nodes', 'Unlimited resources everywhere', 'No constraints exist', 'Only marketing budget limits'], answer: 0 },
  { question: 'Which of the following is a network constraint in application placement?', options: ['Latency and bandwidth', 'Employee headcount', 'Marketing reach', 'Office square footage'], answer: 0 },
  { question: '"Locality requirement" as an application constraint means:', options: ['Certain services\u2019 executions are restricted to specific locations', 'Services can run anywhere with no restriction', 'Services must always run in the cloud', 'Services must always run on mobile devices'], answer: 0 },
  { question: '"Delay sensitivity" as an application constraint means:', options: ['Some applications specify a deadline for processing or deployment', 'Applications never have deadlines', 'All applications run instantly with zero delay', 'Delay is irrelevant to placement'], answer: 0 },
  { question: 'Which of the following is an optimization objective/metric for service placement mentioned in the notes?', options: ['Latency, resource utilization, cost, energy consumption', 'Only marketing reach', 'Only employee satisfaction', 'Only office aesthetics'], answer: 0 },
  { question: 'Offloading, per the notes, is a technique in which:', options: ['A server, an application, and associated data are moved onto the edge of the network', 'Data is deleted permanently', 'All devices are turned off', 'Applications are uninstalled'], answer: 0 },
  { question: '"Offloading from User Device to Edge" augments computing using:', options: ['Edge nodes usually a single hop away', 'Only the cloud several hops away', 'Satellites in geostationary orbit', 'No additional resources'], answer: 0 },
  { question: 'Offloading from User Device to Edge includes which two approaches?', options: ['Application partitioning and Caching mechanisms', 'Marketing and Sales', 'HR and Finance', 'Only manual approaches'], answer: 0 },
  { question: '"Offloading from the Cloud to the Edge" means:', options: ['A workload is moved from the cloud to the edge', 'A workload is moved from the edge to outer space', 'Nothing is moved anywhere', 'All workloads stay in the cloud permanently'], answer: 0 },
  { question: 'Offloading from the Cloud to the Edge includes which two approaches?', options: ['Server offloading and Caching mechanisms', 'Marketing offloading and Sales offloading', 'HR offloading only', 'Only manual approaches'], answer: 0 },
  { question: 'Which of the following is an Application Partitioning approach listed under offloading techniques?', options: ['Brute Force, Greedy Heuristic, Simulated Annealing, Fuzzy Logic', 'Only manual guessing', 'Only random selection', 'Only coin flipping'], answer: 0 },
  { question: 'Which of the following is a partitioning model listed under offloading techniques?', options: ['Graph-based, Component-based, Neural Network-based', 'Only alphabetical ordering', 'Only numeric ordering', 'Only color-based'], answer: 0 },
  { question: 'Under "Server Offloading" (Cloud to Edge), Replication includes which techniques?', options: ['Database Cloning, Application Specific Data Replication', 'Only manual copying with no automation', 'Only deletion', 'Only encryption'], answer: 0 },
  { question: 'Under "Server Offloading" partitioning parameters include:', options: ['Latency-aware, Functionality-aware, Geography-aware', 'Only color-aware', 'Only price-aware', 'Only size-aware'], answer: 0 },
  { question: 'Control architectures for service placement are broadly divided into:', options: ['Centralized and Distributed', 'Marketing and Sales', 'HR and Finance', 'Only Centralized'], answer: 0 },
  { question: 'Which of the following is a Centralized control architecture approach?', options: ['Solver-based, Graph Matching-based', 'Blockchain-based', 'Game Theoretic Approach-based', 'Genetic Algorithm-based'], answer: 0 },
  { question: 'Which of the following is a Distributed control architecture approach?', options: ['Solver-based', 'Blockchain-based, Game Theoretic Approach-based, Genetic Algorithm-based', 'Graph Matching-based only', 'None of these'], answer: 1 },
  { question: 'Fog/edge computing forms a computing environment that uses:', options: ['Low-power devices such as mobile devices, routers, gateways, home systems', 'Only high-power supercomputers', 'Only quantum computers', 'Only mainframes'], answer: 0 },
  { question: 'Combining small-form-factor devices connected to a network enables a cloud computing environment leveraged by applications processing:', options: ['Internet of Things (IoT) and cyber-physical systems (CPS) data', 'Only paper documents', 'Only physical mail', 'Only telegrams'], answer: 0 },
  { question: 'Hardware for fog/edge computing is divided into which two categories?', options: ['Computation Devices and Network Devices', 'Marketing Devices and Sales Devices', 'Only Computation Devices', 'Only Network Devices'], answer: 0 },
  { question: 'Which of the following falls under "Computation Devices" in fog/edge hardware?', options: ['Single-board Computers, Commodity Products', 'Only WiFi APs', 'Only Edge Racks', 'Only Gateways'], answer: 0 },
  { question: 'Which of the following falls under "Network Devices" in fog/edge hardware?', options: ['Gateways and Routers, WiFi APs, Edge Racks', 'Only Single-board Computers', 'Only Commodity Products', 'Only smartphones'], answer: 0 },
  { question: 'A federated cloud (cloud federation) is defined as:', options: ['The deployment and management of multiple external and internal cloud computing services to match business needs', 'A single, standalone private cloud with no external connections', 'A cloud that has been shut down', 'A physical data center with no network'], answer: 0 },
  { question: 'A federation, in general, is defined as:', options: ['The union of several smaller parts that perform a common action', 'A single isolated entity', 'A competition between rival companies', 'A type of firewall'], answer: 0 },
  { question: 'Cloud federation represents collaboration between Cloud Service Providers (CSPs) to achieve which of the following?', options: ['Capacity utilization, inter-operability, catalog of services, insight about providers and SLAs', 'Elimination of all SLAs', 'Reduced interoperability', 'Isolation of all providers from each other'], answer: 0 },
  { question: 'One motivation for forming a cloud federation is:', options: ['Maximizing resource utilization and minimizing power consumption', 'Reducing the number of users served', 'Eliminating load balancing', 'Reducing the CSP\u2019s global footprint'], answer: 0 },
  { question: 'Cloud federation aims to overcome current limitations of cloud computing such as:', options: ['Service interruptions, lack of interoperability, and degradation of services', 'Excessive interoperability', 'Too much reliability', 'Too many available resources'], answer: 0 },
  { question: 'A key characteristic of cloud federation, per the notes, is that it is:', options: ['An inter-cloud organization with voluntary characteristics', 'A mandatory government regulation', 'A single-vendor lock-in model', 'A one-time, non-repeatable event'], answer: 0 },
  { question: 'Typical cloud federation architectures mentioned in the notes include:', options: ['Cloud bursting, brokering, aggregation, and multitier', 'Only cloud bursting', 'Only brokering', 'Only multitier'], answer: 0 },
  { question: 'Federation architectures are classified according to:', options: ['The level of coupling or interoperation among the cloud instances involved', 'The color of the data center building', 'The number of employees at each CSP', 'The marketing budget of each CSP'], answer: 0 },
  { question: 'In a Loosely Coupled Federation, a CSP typically has:', options: ['Little or no control over remote resources', 'Full control over all remote resources', 'Complete access to VM migration features', 'Unlimited advanced networking features'], answer: 0 },
  { question: 'In a Loosely Coupled Federation, monitoring information is typically:', options: ['Limited, e.g., only CPU, memory, or disk consumption reported', 'Completely comprehensive with full system access', 'Nonexistent', 'Only available for marketing purposes'], answer: 0 },
  { question: 'In a Partially Coupled Federation, partner clouds establish:', options: ['A contract or framework agreement stating terms and conditions for resource use', 'No agreement at all', 'A single verbal handshake with no documentation', 'An agreement to never share resources'], answer: 0 },
  { question: 'In a Partially Coupled Federation, contracts can enable:', options: ['Affinity rules, more detailed monitoring information, and some advanced networking features', 'Complete anarchy with no rules', 'Total denial of all resource sharing', 'Removal of all monitoring'], answer: 0 },
  { question: 'In a Tightly Coupled Federation, the clouds are normally:', options: ['Governed by the same cloud administration', 'Governed by completely unrelated, competing administrations', 'Not governed at all', 'Governed only by end users'], answer: 0 },
  { question: 'In a Tightly Coupled Federation, a cloud instance can have advanced control over remote resources, such as:', options: ['Deciding the exact placement of a remote VM', 'No control over anything', 'Only viewing marketing reports', 'Only reading employee schedules'], answer: 0 },
  { question: 'Which advanced features may a Tightly Coupled Federation allow?', options: ['Cross-site networks, cross-site VM migration, high availability, virtual storage across boundaries', 'No features beyond basic email', 'Only spreadsheet sharing', 'Only chat messaging'], answer: 0 },
  { question: 'The Cloud Bursting / Hybrid architecture combines:', options: ['Existing on-premise infrastructure with remote resources from one or more public clouds', 'Two competing private clouds with no connection', 'Only a single public cloud with no private infrastructure', 'Only offline paper records'], answer: 0 },
  { question: 'The Cloud Bursting / Hybrid architecture is typically:', options: ['Loosely coupled', 'Tightly coupled', 'Not coupled at all in any sense', 'Multitier only'], answer: 0 },
  { question: 'In the Broker Architecture, a broker:', options: ['Serves various users and has access to several public cloud infrastructures', 'Has access to only one cloud with no other options', 'Is a physical building with no software', 'Cannot deploy any virtual resources'], answer: 0 },
  { question: 'Brokering, per the notes, is described as:', options: ['The most common federation scenario', 'A rarely used federation scenario', 'Illegal in most jurisdictions', 'Only used once historically'], answer: 0 },
  { question: 'An advanced broker with service management capabilities can make scheduling decisions based on:', options: ['Cost, performance, or energy consumption', 'Random chance only', 'Alphabetical order of cloud names', 'Coin flips'], answer: 0 },
  { question: 'The Broker Architecture is typically:', options: ['Loosely coupled, since public clouds usually do not allow advanced control over deployed resources', 'Always tightly coupled', 'Always multitier', 'Never used in practice'], answer: 0 },
  { question: 'The Aggregated Architecture involves:', options: ['Two or more partner clouds that interoperate to aggregate resources into a larger virtual infrastructure', 'A single cloud with no partners', 'Complete isolation between all clouds', 'Only public clouds with no private infrastructure'], answer: 0 },
  { question: 'The Aggregated Architecture is usually:', options: ['Partially coupled', 'Always loosely coupled with zero control', 'Always tightly coupled with full control', 'Not a real architecture'], answer: 0 },
  { question: 'According to the notes, partner clouds in an Aggregated Architecture usually have a higher coupling level when they:', options: ['Belong to the same corporation rather than different companies', 'Belong to entirely different, unrelated companies', 'Have no contract at all', 'Are located on different planets'], answer: 0 },
  { question: 'The Multitier Architecture involves two or more cloud sites managed by:', options: ['A third cloud OS instance following a hierarchical arrangement', 'No management at all', 'Only manual human intervention with no software', 'A rival company\u2019s cloud OS'], answer: 0 },
  { question: 'In the Multitier Architecture, the root/top cloud OS instance has:', options: ['Full control over resources in different cloud sites (a tightly coupled scenario)', 'No control over any resources', 'Only read-only access', 'Control over marketing budgets only'], answer: 0 },
  { question: 'The Multitier Architecture is beneficial for corporations with:', options: ['Geographically distributed cloud infrastructures, because it provides uniform access', 'A single data center in one city only', 'No cloud infrastructure at all', 'Only on-premise paper filing systems'], answer: 0 },
  { question: 'The Multitier Architecture may be useful for implementing which advanced management features?', options: ['High availability, load balancing, and fault tolerance', 'Only cosmetic branding', 'Only marketing emails', 'Only invoice generation'], answer: 0 },
];

/* ---------------- Notes view ---------------- */

function NotesView() {
  return (
    <div className="space-y-6">
      {notes.map((section, i) => (
        <div key={i} className="rounded-xl border border-slate-700 bg-slate-800/60 p-5">
          <h3 className="mb-3 font-semibold text-indigo-300">{section.heading}</h3>
          <ul className="space-y-2">
            {section.items.map((item, j) => (
              <li key={j} className="flex gap-3 text-sm leading-relaxed text-slate-300">
                <span className="mt-2 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-amber-400" />
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
      ))}
    </div>
  );
}

/* ---------------- Practice / Quiz view ---------------- */

function QuestionSet({ mode }: { mode: 'practice' | 'quiz' }) {
  const [selected, setSelected] = useState<(number | null)[]>(Array(questions.length).fill(null));
  const [submitted, setSubmitted] = useState(false);

  const choose = (qIndex: number, optIndex: number) => {
    if (mode === 'practice') {
      if (selected[qIndex] !== null) return;
    } else if (submitted) {
      return;
    }
    const next = [...selected];
    next[qIndex] = optIndex;
    setSelected(next);
  };

  const reset = () => {
    setSelected(Array(questions.length).fill(null));
    setSubmitted(false);
  };

  const answeredCount = selected.filter((s) => s !== null).length;
  const score = selected.reduce((acc: number, s, i) => (s === questions[i].answer ? acc + 1 : acc), 0);
  const showFeedback = (qIndex: number) => (mode === 'practice' ? selected[qIndex] !== null : submitted);

  return (
    <div className="space-y-6">
      <div className="sticky top-0 z-10 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-700 bg-slate-900/95 p-4 backdrop-blur">
        <div className="text-sm text-slate-300">
          <span className="font-semibold text-slate-100">{answeredCount}</span> / {questions.length} answered
          {mode === 'quiz' && submitted && (
            <span className="ml-3 font-semibold text-amber-400">
              Score: {score} / {questions.length} ({Math.round((score / questions.length) * 100)}%)
            </span>
          )}
        </div>
        <div className="flex gap-2">
          {mode === 'quiz' && !submitted && (
            <button
              onClick={() => setSubmitted(true)}
              disabled={answeredCount === 0}
              className="rounded-lg bg-indigo-500 px-4 py-2 text-sm font-medium text-white transition hover:bg-indigo-400 disabled:cursor-not-allowed disabled:bg-slate-700 disabled:text-slate-500"
            >
              Submit quiz
            </button>
          )}
          <button
            onClick={reset}
            className="flex items-center gap-1.5 rounded-lg border border-slate-600 px-3 py-2 text-sm text-slate-300 transition hover:border-slate-500 hover:text-white"
          >
            <RotateCcw size={14} /> Reset
          </button>
        </div>
      </div>

      {questions.map((q, qi) => {
        const userAns = selected[qi];
        const feedback = showFeedback(qi);
        return (
          <div key={qi} className="rounded-xl border border-slate-700 bg-slate-800/60 p-5">
            <p className="mb-4 text-sm font-medium text-slate-100">
              <span className="mr-2 text-indigo-400">Q{qi + 1}.</span>
              {q.question}
            </p>
            <div className="grid gap-2 sm:grid-cols-2">
              {q.options.map((opt, oi) => {
                const isSelected = userAns === oi;
                const isCorrectOpt = oi === q.answer;
                let stateClasses = 'border-slate-600 bg-slate-800 hover:border-indigo-400 hover:bg-slate-750 text-slate-200';

                if (feedback) {
                  if (isCorrectOpt) stateClasses = 'border-emerald-500 bg-emerald-500/10 text-emerald-300';
                  else if (isSelected && !isCorrectOpt) stateClasses = 'border-rose-500 bg-rose-500/10 text-rose-300';
                  else stateClasses = 'border-slate-700 bg-slate-800/50 text-slate-500';
                } else if (isSelected) {
                  stateClasses = 'border-indigo-400 bg-indigo-500/10 text-indigo-200';
                }

                return (
                  <button
                    key={oi}
                    onClick={() => choose(qi, oi)}
                    className={`flex items-center justify-between rounded-lg border px-3 py-2.5 text-left text-sm transition ${stateClasses}`}
                  >
                    <span>
                      <span className="mr-2 font-semibold">{String.fromCharCode(65 + oi)}.</span>
                      {opt}
                    </span>
                    {feedback && isCorrectOpt && <Check size={16} className="flex-shrink-0 text-emerald-400" />}
                    {feedback && isSelected && !isCorrectOpt && <X size={16} className="flex-shrink-0 text-rose-400" />}
                  </button>
                );
              })}
            </div>
            {mode === 'practice' && feedback && (
              <p className={`mt-3 text-xs font-medium ${userAns === q.answer ? 'text-emerald-400' : 'text-rose-400'}`}>
                {userAns === q.answer ? 'Correct!' : `Not quite — the correct answer is "${q.options[q.answer]}".`}
              </p>
            )}
          </div>
        );
      })}
    </div>
  );
}

/* ---------------- Module 9 page ---------------- */

export default function Module9Page({ view }: { view: ViewType }) {
  return (
    <div>
      <div className="mb-6">
        <p className="text-xs font-medium uppercase tracking-wider text-indigo-400">
          Module 09 — {view.charAt(0).toUpperCase() + view.slice(1)}
        </p>
        <h1 className="mt-1 text-2xl font-bold text-slate-100">
          Cloud Computing Paradigm: Cloud-Fog Computing, Resource Management, Service Placement &amp; Cloud Federation
        </h1>
        {view === 'practice' && (
          <p className="mt-2 text-sm text-slate-400">
            Pick an answer to instantly see if it&apos;s correct — great for learning as you go.
          </p>
        )}
        {view === 'quiz' && (
          <p className="mt-2 text-sm text-slate-400">
            Answer all the questions, then submit to see your score and review your answers.
          </p>
        )}
      </div>

      {view === 'notes' && <NotesView />}
      {view === 'practice' && <QuestionSet mode="practice" />}
      {view === 'quiz' && <QuestionSet mode="quiz" />}
    </div>
  );
}